<a href="https://colab.research.google.com/github/ValdazoAmerico/word2vec-keras/blob/main/word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# define tokenized senences as training data
tokenized_sentences = [['Hello','This','is','python','training','by','Aman'],
             ['Hello','This','is','Java','training','by','Aman'],
             ['Hello','This','is','Data Science','training','by','Unfold','Data','Science'],
             ['Hello','This','is','programming','training','']]

In [2]:
# training word2vec model
from gensim.models import Word2Vec
import warnings
warnings.filterwarnings('ignore')
mymodel = Word2Vec(tokenized_sentences, min_count=1)

In [4]:
# summarizing the loaded model
print(mymodel)

Word2Vec(vocab=14, size=100, alpha=0.025)


In [5]:
# summarize vocabulary
words = list(mymodel.wv.vocab)

In [6]:
# summarize vocabulary
print(words)

['Hello', 'This', 'is', 'python', 'training', 'by', 'Aman', 'Java', 'Data Science', 'Unfold', 'Data', 'Science', 'programming', '']


In [7]:
# access word vector for one word "training"
print(mymodel['Hello'])

[-4.4044652e-03  4.9070278e-03 -2.7047102e-03  4.7178846e-03
  1.3772162e-03  1.4945143e-03  4.4133505e-04 -4.2476133e-04
  2.8311354e-03 -4.9011246e-03 -3.6036121e-03  4.9806824e-03
  2.8197160e-03 -4.5372266e-03  4.1466020e-03  3.0684252e-03
  3.3007860e-03  2.1379394e-03  4.4266558e-03 -1.8094338e-03
  2.4746740e-03 -4.9665282e-03  4.5673354e-03  2.0000888e-03
  1.4826180e-03  1.5776806e-03  2.9162476e-03 -3.8847307e-04
  4.6997113e-04  1.0693220e-04 -2.0516613e-03  1.7415115e-03
  3.6198201e-03  3.6840821e-03  2.6954962e-03 -2.9150436e-03
 -4.2709629e-03  9.1733702e-04 -4.4796169e-03 -4.7485554e-03
  4.2468770e-03  9.1044011e-04  4.5716926e-03 -8.3382573e-04
  2.1438312e-03  4.4055353e-03  2.8207737e-03 -4.6060574e-03
  3.4557017e-03  3.1898140e-03  4.1027716e-04  2.1842020e-03
 -4.3838583e-03 -4.9232310e-03  1.6103372e-03  1.8358512e-03
 -1.1286444e-03  2.9872844e-03  4.8790406e-03 -3.1404421e-04
 -4.3104570e-03 -3.2315927e-03  7.2957882e-05  1.6539531e-03
 -1.4546411e-03  2.74941

In [10]:
#try finding most similar words for word "Data"
mymodel.most_similar("Data Science")

[('programming', 0.21485498547554016),
 ('is', 0.05362511798739433),
 ('Data', 0.045679740607738495),
 ('This', 0.04408987611532211),
 ('by', 0.027149155735969543),
 ('Unfold', -0.001469602808356285),
 ('', -0.008109666407108307),
 ('Java', -0.021059472113847733),
 ('Hello', -0.037318285554647446),
 ('Aman', -0.03969716280698776)]

# Word2vec and Keras

In [11]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
Sent = ['Hello, how are you',
        'how are you',
        'how are you doing',
        'I am doing great',
        'I am doing good',
        'I am good']

In [12]:
# defining class labels
sent_labels = array([1,1,1,0,0,0])

In [13]:
# integer encoding of the documents
my_vocab_size = 30
encoded_sent = [one_hot(i, my_vocab_size) for i in Sent]
print(encoded_sent)

[[15, 13, 14, 24], [13, 14, 24], [13, 14, 24, 7], [1, 23, 7, 18], [1, 23, 7, 24], [1, 23, 24]]


In [14]:
# padding documents to a max length =5 
length = 5
padded_sent = pad_sequences(encoded_sent, maxlen=length, padding='pre')
print(padded_sent)

[[ 0 15 13 14 24]
 [ 0  0 13 14 24]
 [ 0 13 14 24  7]
 [ 0  1 23  7 18]
 [ 0  1 23  7 24]
 [ 0  0  1 23 24]]


In [16]:
# defining the model
mymodel = Sequential()
mymodel.add(Embedding(my_vocab_size, 8, input_length=length))
mymodel.add(Flatten())
mymodel.add(Dense(1, activation='sigmoid'))


In [17]:
# compiling the model
mymodel.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [21]:
# fiting  the model
mymodel.fit(padded_sent, sent_labels, epochs=30)

# evaluate the model
modelloss, modelaccuracy = mymodel.evaluate(padded_sent, sent_labels, verbose=0)
print('Accuracy: %f' % (modelaccuracy*100))

Epoch 1/30
1/1 [==============================] - 0s 5ms/step - loss: 0.6208 - accuracy: 1.0000
Epoch 2/30
1/1 [==============================] - 0s 4ms/step - loss: 0.6188 - accuracy: 1.0000
Epoch 3/30
1/1 [==============================] - 0s 3ms/step - loss: 0.6168 - accuracy: 1.0000
Epoch 4/30
1/1 [==============================] - 0s 7ms/step - loss: 0.6148 - accuracy: 1.0000
Epoch 5/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6128 - accuracy: 1.0000
Epoch 6/30
1/1 [==============================] - 0s 5ms/step - loss: 0.6107 - accuracy: 1.0000
Epoch 7/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6086 - accuracy: 1.0000
Epoch 8/30
1/1 [==============================] - 0s 5ms/step - loss: 0.6066 - accuracy: 1.0000
Epoch 9/30
1/1 [==============================] - 0s 3ms/step - loss: 0.6045 - accuracy: 1.0000
Epoch 10/30
1/1 [==============================] - 0s 5ms/step - loss: 0.6024 - accuracy: 1.0000
Epoch 11/30
1/1 [======================

In [22]:
mysent_to_predict = ['how are you Suman',
        'I am good']

In [23]:
# integer encode the documents
vocab_size = 30
encoded = [one_hot(d, vocab_size) for d in mysent_to_predict]
print(encoded)


[[13, 14, 24, 13], [1, 23, 24]]


In [24]:
# pad documents to a max length of 5 words
max_length = 5
mypadded = pad_sequences(encoded, maxlen=max_length, padding='pre')
print(mypadded)

[[ 0 13 14 24 13]
 [ 0  0  1 23 24]]


In [25]:
mymodel.predict_classes(mypadded)

array([[1],
       [0]], dtype=int32)